name: choco

on:
  push:
    branches-ignore:
        - "ga-ignore-*"
  pull_request:
    branches-ignore:
        - "ga-ignore-*"

jobs:
  check_program_compilation:
    runs-on: ubuntu-latest
    env:
      EXECUTABLE: chocolatine
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: make
      - run: make clean
      - run: |
          if [ ! -f ${{ env.EXECUTABLE }} ]; 
          then
            echo "File is not exist"
            exit 1
          fi
          if [ ! -x ${{ env.EXECUTABLE }}]
            then
              echo "executable is not exist"
              exit 1
          fi

  push_to_mirror:
    runs-on: ubuntu-latest
    env:
      MIRROR_URL: git@github.com:EpitechPGEPromo2029/B-DOP-200-PAR-2-1-chocolatine-maxime.kournikov.git
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}

